name: Build wheels for ASD_GUI

on: [release]
#on: [release, push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { icon: 'ðŸ§' , os: ubuntu-latest,  shell: bash, arch: x86_64 }
          - { icon: 'ðŸ’»' , os: windows-latest, shell: msys2, arch: x86_64 }
          - { icon: 'ðŸŽ' , os: macos-14,       shell: bash, arch: arm64 }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      #- name: Install patched cibuildwheel for Windows ${{ matrix.icon}}
      #  if: runner.os == 'Windows'
      #  #run: python -m pip install cibuildwheel==2.10.1
      #  run: |
      #      python -m ensurepip 
      #      python -m pip install git+https://github.com/anbergman/cibuildwheel.git@purepath
      #  #   python -m pip install ninja numpy scipy

      #- name: Build wheels on Windows ${{ matrix.icon}}
      #  if: runner.os == 'Windows'
      #  run: |
      #    which gfortran
      #    pipx run cibuildwheel --output-dir wheelhouse
      #  # python -m cibuildwheel --output-dir wheelhouse
      #  # to supply options, put them in 'env', like:
      #  # env:
      #  #   CIBW_SOME_OPTION: value
      #  env:
      #    CIBW_ENVIRONMENT_WINDOWS: >
      #     CMAKE_PREFIX_PATH="\msys64\mingw64" CC=gcc CXX=g++ FC=gfortran 

      - name: Build wheels on Linux and macOS ${{ matrix.icon}}
        uses: pypa/cibuildwheel@v2.18.1
        #if: runner.os != 'Windows'
        with:
          package-dir: ./ASD_GUI
          output-dir: wheelhouse
          # to supply options, put them in 'env', like:

      - uses: actions/upload-artifact@v4
        with:
          name: asdgui.${{matrix.os}}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build
        run: python -m pip install build wheel setuptools

      - name: Build source distribution
        run: |
          cd ASD_GUI
          python -m build . --sdist
          cd ..

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asdgui_sdist
          path: ASD_GUI/dist

